apiVersion: v1
kind: Service
metadata:
  name: gtsr
spec:
  type: NodePort
  clusterIP: 10.96.0.2
  ports:
  - nodePort: 30000
    port: 6666
    protocol: TCP
    targetPort: 5000
  selector:
    run: gtsr